---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=autograph
install: 
  - source ~/.cargo/env || true
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - cargo test --lib 
