---
cache: cargo
dist: xenial
env: 
  global: 
    - CRATE_NAME=autograph
install: 
  - source ~/.cargo/env || true
language: rust
env: TARGET=x86_64-unknown-linux-gnu
notifications: 
  email: 
    on_success: never
script:
  - while sleep 540; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - cargo build
  - cargo test --lib
  - cargo build --examples --features datasets
  - cargo build --benches 
  - kill %1
