[package]
name = "autograph"
version = "0.0.1"
authors = ["charles-r-earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Machine Learning Library built on ndarray."
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"

[dependencies]
cpp = "0.5.4"
rustacuda = { version = "0.1.2", optional = true }
cuda-sys = { version = "0.2.0", optional = true }
num-traits = "0.2.11"


[build-dependencies]
cmake = "0.1.42"
cpp_build = "0.5.4"


[features]
cuda = ["rustacuda", "cuda-sys"]


