[package]
name = "autograph"
version = "0.0.1"
authors = ["charles-r-earp <charles.r.earp@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Machine Learning Library built on ndarray."
homepage = "https://github.com/charles-r-earp/autograph"
repository = "https://github.com/charles-r-earp/autograph"

[dependencies]
ndarray = "0.13.0"
num-traits = "0.2.8"
rand = "0.7.2"
rand_distr = "0.2.2"
reqwest = "0.9.22"
flate2 = "1.0.12"
byteorder = "1.3.2"
timeit = "0.1.2"
matrixmultiply = "0.2.3"
args = "2.2.0"
getopts = "0.2.21"
progress = "0.2.0"
terminal_size = "0.1.8"

