name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }} 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Check
      run: cargo check --verbose --features datasets
    - name: Check Bins
      run: cargo check --bins --verbose --features datasets
    - name: Build
      run: cargo build --verbose --features datasets
    - name: Build Bins
      run: cargo build --bins --verbose --features datasets
    - name: Run tests
      run: cargo test --lib --verbose
    - name: Run MNIST Dense Example
      run: cargo run --example mnist_dense --verbose --features datasets -- --epochs 1
    - name: Run MNIST Lenet5 Example
      run: cargo run --example mnist_lenet5 --verbose --features datasets -- --epochs 1
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Bench
      run: cargo bench
