name: Rust

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --features datasets
    - name: Run tests
      run: cargo test --lib --verbose
    - name: Check all binary targets
      run: cargo check --bins --verbose --features datasets
