name: Rust

on:
  push:
    branches: [ dynamic ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --lib --verbose
    - name: Run examples as tests
      run: cargo test --examples --verbose --features datasets
